# Создание новой публикации
POST http://localhost:3002/api/post/create HTTP/1.1
Content-Type: application/json

{
    "type": "video",
    "status": "published",
    "tags": ["test"],
    "videoTitle": "Test video title",
    "videoUrl" : "https://youtu.be/aboba",
    "userId" : "62fdcda5-2efa-4ea9-aa3a-bf7829fc7ba5"
}
###

# Получение публикации по id
GET http://localhost:3002/api/post/c163f24e-c264-475c-a989-2bc36704b94a HTTP/1.1
###

# Изменение публикации
PUT http://localhost:3002/api/post/update/20d6bf11-7c9c-45b5-9c3c-15e4534525ba HTTP/1.1
Content-Type: application/json

{
    "type": "video",
    "status": "draft",
    "tags": ["test"],
    "videoTitle": "Test video title - CHANGED",
    "videoUrl" : "https://youtu.be/test123",
    "userId" : "62fdcda5-2efa-4ea9-aa3a-bf7829fc7ba5"
}
###

# Удаление публикации
DELETE http://localhost:3002/api/post/delete/20d6bf11-7c9c-45b5-9c3c-15e4534525ba HTTP/1.1
Content-Type: application/json

{
    "userId" : "62fdcda5-2efa-4ea9-aa3a-bf7829fc7ba5"
}
###

# Репост публикации
POST http://localhost:3002/api/post/repost/c163f24e-c264-475c-a989-2bc36704b94a HTTP/1.1
###

# Добавление лайка
POST http://localhost:3002/api/post/addLike/c163f24e-c264-475c-a989-2bc36704b94a HTTP/1.1
###

# Удаление лайка
POST http://localhost:3002/api/post/deleteLike/c163f24e-c264-475c-a989-2bc36704b94a HTTP/1.1
###

# Список публикаций
GET http://localhost:3002/api/post HTTP/1.1
###

# Поиск публикаций
GET http://localhost:3002/api/post/search/video HTTP/1.1
###