# Создание нового комментария
POST http://localhost:3002/api/post-comment/create HTTP/1.1
Content-Type: application/json

{
    "postId": "929fc82f-43eb-4744-8329-768434ac7a08",
    "commentText": "Test comment text - 2"
}
###

# Удаление комментария
DELETE http://localhost:3002/api/post-comment/delete/c0285445-f291-47a9-b0fd-f77dff05dd0b HTTP/1.1
###

# Получение комментариев по id публикации
GET http://localhost:3002/api/post-comment/?postId=929fc82f-43eb-4744-8329-768434ac7a08 HTTP/1.1
###